mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from django.contrib import messages


class CustomLogoutView(LogoutView):
    def dispatch(self, request, *args, **kwargs):
        messages.success(request, "You have successfully logged out.")
        return super().dispatch(request, *args, **kwargs)


urlpatterns = [
    path('register/', views.register, name='register'),
    path('success/', views.success, name='success'),
    path('login/', views.login_view, name='login'),
    path('admin/', admin.site.urls),
    path('home/', views.home, name='home'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('test/', views.test, name='test'),
    path('update_user_answer/', views.update_user_answer, name='update_user_answer'),
    path('user_history/<str:username>/', views.get_user_history, name='user_history'),
    path('all_users_history/', views.get_all_users_history, name='all_users_history'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from django.contrib import messages


class CustomLogoutView(LogoutView):
    def dispatch(self, request, *args, **kwargs):
        messages.success(request, "You have successfully logged out.")
        return super().dispatch(request, *args, **kwargs)


urlpatterns = [
    path('register/', views.register, name='register'),
    path('', views.index, name='index'),
    path('success/', views.success, name='success'),
    path('login/', views.login_view, name='login'),
    path('admin/', admin.site.urls),
    path('home/', views.home, name='home'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('test/', views.test, name='test'),
    path('update_user_answer/', views.update_user_answer, name='update_user_answer'),
    path('user_history/<str:username>/', views.get_user_history, name='user_history'),
    path('all_users_history/', views.get_all_users_history, name='all_users_history'),
    # path('next_question/', views.next_question, name='next_question'),

]

mysite/mysite/models.py
from django.db import models
from django.contrib.auth.models import User

class Question(models.Model):
    passage = models.TextField()
    question_text = models.TextField()
    choices = models.JSONField()
    answer = models.CharField(max_length=1)
    knowledge_component = models.CharField(max_length=50)
    id = models.IntegerField(primary_key=True)

    def __str__(self):
        return self.question_text

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    history = models.TextField(blank=True, default='')

class UserAnswer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.CharField(max_length=1)
    correct = models.BooleanField(default=False)

    class Meta:
        unique_together = ('user', 'question')

mysite/mysite/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['email', 'password']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            self.add_error('confirm_password', "Passwords don't match")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        user.username = user.email

        if commit:
            user.save()

            user_profile = UserProfile(user=user)
            user_profile.save()

        return user

mysite/mysite/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.auth.decorators import login_required

from django.db.models import Count
from django.db.models.functions import Random
from .models import Question
import random
from .models import UserAnswer
from django.http import JsonResponse

from django.core import serializers
from django.contrib.auth.decorators import user_passes_test
from django.contrib.admin.views.decorators import staff_member_required

@login_required
def home(request):
    return render(request, 'home.html', {'user': request.user})

def register(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password != confirm_password:
            messages.error(request, 'Passwords do not match.')
            return redirect('register')

        if User.objects.filter(email=email).exists():
            messages.error(request, 'An account with this email address already exists.')
            return redirect('register')
        else:
            user = User.objects.create_user(username=email, email=email, password=password)
            user.save()
            messages.success(request, 'Account created successfully!')
            return redirect('home')

    return render(request, 'register.html')

def login_view(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, username=email, password=password)

        if user is not None:
            auth_login(request, user)
            messages.success(request, 'Logged in successfully!')
            return redirect('home')
        else:
            messages.error(request, 'Invalid email or password.')

    return render(request, 'login.html')

@login_required
def test(request):
    user = request.user
    answered_questions = UserAnswer.objects.filter(user=user).values_list('question_id', flat=True)
    unanswered_questions = Question.objects.exclude(id__in=answered_questions)
    questions_count = Question.objects.count()
    answered_questions_count = answered_questions.count()

    if unanswered_questions:
        question = random.choice(unanswered_questions)

        if request.method == 'POST':
            selected_choice = request.POST['selected_choice']
            user_answer = UserAnswer(user=request.user, question=question, answer=selected_choice)
            user_answer.save()

        return render(request, 'test.html', {'question': question, 'questions_count': questions_count, 'answered_questions_count': answered_questions_count})
    else:
        return render(request, 'done.html')

    

def success(request):
    return render(request, 'success.html')


def update_user_answer(request):
    print("Request method: ", request.method)
    print("X-Requested-With header: ", request.headers.get('X-Requested-With'))
    if request.method == 'POST' and request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        user_id = request.user.id
        question_id = request.POST.get('question_id')
        selected_answer = request.POST.get('selected_answer')

        print("User ID: ", user_id)
        print("Question ID: ", question_id)
        print("Selected Answer: ", selected_answer)

            # Get the correct answer for the question
        question = Question.objects.get(id=question_id)
        correct_answer = question.answer

        # Get the index of the selected answer (A, B, C, D)
        answer_choices = question.choices
        selected_answer_index = answer_choices.index(selected_answer)

        # Map the index to a corresponding letter
        index_to_letter = {0: 'A', 1: 'B', 2: 'C', 3: 'D'}
        selected_answer_letter = index_to_letter[selected_answer_index]

        # Compare the user's selected answer letter to the correct answer
        is_correct = selected_answer_letter == correct_answer

        # Update or create the UserAnswer
        user_answer, created = UserAnswer.objects.update_or_create(
            user_id=user_id, question_id=question_id,
            defaults={'answer': selected_answer_letter, 'correct': is_correct} # Update the 'correct' field here
        )
        user_answer.save()

        return JsonResponse({'message': 'UserAnswer updated'}, status=200)
    else:
        return JsonResponse({'error': 'Invalid request'}, status=400)

@user_passes_test(lambda u: u.is_staff)  # Ensure that the user is an admin
def get_user_history(request, username):
    if username:
        target_user = User.objects.get(username=username)
        user_answers = UserAnswer.objects.filter(user=target_user)
        formatted_answers = []

        for answer in user_answers:
            formatted_answers.append({
                'question_id': answer.question.id,
                'correct': int(answer.correct)
            })

        return JsonResponse({'user_history': formatted_answers})
    else:
        return JsonResponse({'error': 'Invalid request'}, status=400)

@user_passes_test(lambda u: u.is_staff)  # Ensure that the user is an admin
def get_all_users_history(request):
    all_users = User.objects.all()
    all_users_history = []

    for user in all_users:
        user_answers = UserAnswer.objects.filter(user=user)
        formatted_answers = []

        for answer in user_answers:
            formatted_answers.append({
                'question_id': answer.question.id,
                'correct': int(answer.correct)
            })

        user_history = {
            'username': user.username,
            'history': formatted_answers
        }
        all_users_history.append(user_history)

    return JsonResponse({'all_users_history': all_users_history})
    


@staff_member_required
def admin_dashboard(request):
    return render(request, 'admin_dashboard.html')

mysite/mysite/templates/admin_dashboard.html
{% extends "base.html" %}

{% block content %}
  <h1>Admin Dashboard</h1>

  <h2>User History</h2>
  <label for="user-id">User ID:</label>
  <input type="number" id="user-id" name="user-id" min="1">
  <button id="fetch-history-btn">Fetch History</button>

  <pre id="user-history-output"></pre>

  <script>
    document.getElementById('fetch-history-btn').addEventListener('click', function() {
      const targetUserId = document.getElementById('user-id').value;

      fetch(`/get_user_history/?user_id=${targetUserId}`)
        .then(response => response.json())
        .then(data => {
          const userHistory = data.user_history;
          console.log(userHistory);

          document.getElementById('user-history-output').innerText = JSON.stringify(userHistory, null, 2);
        });
    });
  </script>
{% endblock %}

mysite/mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AIComprehend</title>
    <link rel="icon" href="{% static 'mysite/logo-icon.png' %}" type="image/x-icon">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600;700&family=Source+Sans+3:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'mysite/style.css' %}">
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

mysite/mysite/templates/done.html
{% extends "base.html" %}
{% block content %}
  <h2>Done</h2>
  <p>You have answered all the questions!</p>
{% endblock %}

mysite/mysite/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% if user.is_authenticated %}
<div class="navbar">
    <div class="nav-logo"><img src="{% static 'mysite/logo.png' %}" width="250px", height="auto"></div>
    <div class="nav-links">
        <a class="nav-link" href="{% url 'home' %}"><span class="active-page">Home</span></a>
        <a class="nav-link" href="{% url 'test' %}">Test</a>
        <a class="nav-link" href="{% url 'logout' %}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</a>
        <form id="logout-form" method="post" action="{% url 'logout' %}" style="display:none;">
            {% csrf_token %}
        </form>
    </div>
</div>

<div id="home-content">
    <!-- Empty body -->
    <div class="text-container">
        <h1 id="home-header">Improve your reading comprehension skills with AIComprehend!</h1>
        <p id="home-paragraph">Unleash your inner reading champion with AIComprehend! Our app uses machine learning to customize reading materials for you, with curated and engaging passages and questions. Try it now and discover the joy of learning!</p>
        <a href="https://www.youtube.com/watch?v=W7BW9gv_OkU"><button id="home-button">Watch the tutorial</button></a>
    </div>

    <img src="{% static 'mysite/home-splash-2.png' %}" class="home-splash">
</div>
{% endif %}

{% endblock %}

mysite/mysite/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div id="login-left-bg">
    <div id="text-content">
      <h1 id="left-title">Adventure Starts Here</h1>
      <h2 id="left-paragraph">Create an account to join our community of readers and learners!</h2>
    </div>
  </div>

  <!-- Right Part -->
  <div class="form-content">

    {% for message in messages %}
    <div class="{% if message.tags %}alert-{{ message.tags }}{% endif %}">
        <span class="alert-message">
            {{ message }}
        </span>
    </div>
    {% endfor %}

    <img src="{% static 'mysite/logo-icon.png' %}" id="icon" width="120px" height="auto">
    <h1 id="login-title"> Hello! Welcome Back</h1>
    <form method="post">
      {% csrf_token %}
      <label for="email">Email:</label><br>

      <div class="input-field">
        <input type="email" id="email" name="email" placeholder="Enter your email address" required>
        <img src="{% static 'mysite/email-icon.png' %}">
      </div>     
  
      <label for="password">Password:</label><br>
      <div class="input-field">
        <input type="password" id="password" name="password" placeholder="••••••••" required>
        <img src="{% static 'mysite/password-icon.png' %}">
      </div>
  
      <button type="submit">Login</button>
    </form>
    <p>Don't have an account? <a href="{% url 'register' %}" id="link-text">Register here</a></p>
  </div>
  
{% endblock %}

mysite/mysite/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <body width="1512px" heigh="870px">
    <div id="signup-left-bg">
      <div id="text-content">
        <h1 id="left-title">AIComprehend</h1>
        <h2 id="left-paragraph">Improve your reading comprehension skills right now for free!</h2>
      </div>
    </div>

    <div class="form-content">
        {% for message in messages %}
        <div class="{% if message.tags %}alert-{{ message.tags }}{% endif %}">
            <span class="alert-message">
                {{ message }}
            </span>
        </div>
        {% endfor %}

      <!-- <img src="media/logo-icon.png" id="icon" width="120px" height="auto"> -->
      <h1 id="signup-title"> Create your account!</h1>
      <form method="post" action="{% url 'register' %}">
        {% csrf_token %}
        <label for="email">Email:</label><br>
        <div class="input-field">
          <input type="email" id="email" name="email" placeholder="Enter your email address" required>
          <img src="{% static 'mysite/email-icon.png' %}">
        </div>      
  
        <label for="password">Password:</label><br>
        <div class="input-field">
          <input type="password" id="password" name="password" placeholder="••••••••" required>
          <img src="{% static 'mysite/password-icon.png' %}">
        </div>
        
        <label for="confirm_password">Confirm Password:</label><br>
        <div class="input-field">
          <input type="password" id="confirm_password" name="confirm_password" placeholder="••••••••" required>
          <img src="{% static 'mysite/password-icon.png' %}">
        </div>
  
        <button type="submit" value="Sign Up">Register</button>
      </form>
      <p>Already have an account? <a href="{% url 'login' %}" id="link-text">Login here</a></p>
    </div>
    
  </body>

{% endblock %}

mysite/mysite/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Success</title>
</head>
<body>
    <h1>Registration Successful!</h1>
</body>
</html>

mysite/mysite/templates/test.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% load custom_filters %}
<div class="navbar">
    <div class="nav-logo"><img src="{% static 'mysite/logo.png' %}" width="250px", height="auto"></div>
    <div class="nav-links">
        <a class="nav-link" href="{% url 'home' %}">Home</a>
        <a class="nav-link" href="{% url 'test' %}"><span class="active-page">Test</span></a>
        <a class="nav-link" href="{% url 'logout' %}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</a>
        <form id="logout-form" method="post" action="{% url 'logout' %}" style="display:none;">
            {% csrf_token %}
        </form>
    </div>
</div>
<div class="progress-container">
    <div class="progress-bar" id="progress-bar" style="width: 0%;"></div>
  </div>
  <script>
    const answeredQuestionsCount = "{{ answered_questions_count }}";
    const totalQuestionsCount = "{{ questions_count }}";
  
    function updateProgressBar() {
      const progressBar = document.getElementById('progress-bar');
      const progress = (answeredQuestionsCount / totalQuestionsCount) * 100;
  
      progressBar.style.width = progress + '%';
    }
  
    updateProgressBar();
  </script>
<div class="test-content">
    <button id="exit-btn" onclick="handleExitClick()" class="exit-btn">X</button>

    <h3>Question {{ user.useranswer_set.count|add:"1" }}/{{ questions_count }}</h3>
    <p id="passage">{{ question.passage }}</p>

  <!-- <h3>Question:</h3> -->
  <p id="question">{{ question.question_text }}</p>

  <form id="answer-form" method="post">
    {% csrf_token %}
    <input type="hidden" name="selected_choice" id="selected_choice" value="">
    
    <script>
    function handleExitClick() {
        window.location.href = "{% url 'home' %}";
    }

        
    let submitted = false;

    function handleChoiceClick(button) {
        if (submitted) {
            return;
        }

        let choiceButtons = document.getElementsByClassName('choice-btn');
        let submitButton = document.getElementById('submit-btn');
        
        // If the button is already selected, deselect it
        if (button.classList.contains('selected')) {
            button.classList.remove('selected');
            submitButton.disabled = true;
            return;
        }
        
        // Clear previous selection
        for (let i = 0; i < choiceButtons.length; i++) {
            choiceButtons[i].classList.remove('selected');
        }
        
        // Highlight the selected button
        button.classList.add('selected');
        submitButton.disabled = false;
        document.getElementById('selected_choice').value = button.innerText;
    }
    
    function handleSubmit(event) {
        event.preventDefault();
        let nextButton = document.getElementById('next-btn');
        let submitButton = document.getElementById('submit-btn');
        let resultMessage = document.getElementById('result-message');
        let answer = document.querySelector('.selected').innerText;
        let correctAnswer = "{{ question.choices|get_item:question.answer|force_escape }}";
        let correctChoice = "{{ question.choices|get_item:question.answer|force_escape }}";

        let alertDiv = document.createElement('div');
        alertDiv.classList.add('alert-message');

        if (answer === correctAnswer) {
            alertDiv.innerText = "Correct!";
            alertDiv.classList.add('alert-success');
        } else {
            alertDiv.innerHTML = "Incorrect! The correct answer is: " + unescape(correctChoice);
            alertDiv.classList.add('alert-error');
        }
        
        resultMessage.innerHTML = '';
        resultMessage.appendChild(alertDiv);
        nextButton.disabled = false;

        let questionId = "{{ question.id }}";
        updateUserAnswer(questionId, answer); // Call the updateUserAnswer function here

        // Disable the submit button
        submitButton.disabled = true;
        submitted = true;
    }




function updateUserAnswer(questionId, selectedAnswer) {
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
    const xhttp = new XMLHttpRequest();

    xhttp.onreadystatechange = function () {
        if (this.readyState === 4 && this.status === 200) {
            console.log("UserAnswer updated");
        } else if (this.readyState === 4) {
            console.log("Error updating UserAnswer");
        }
    };

    xhttp.open("POST", "/update_user_answer/", true);
    xhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
    xhttp.setRequestHeader("X-Requested-With", "XMLHttpRequest"); // Make sure to include this header
    xhttp.setRequestHeader("X-CSRFToken", csrftoken);
    xhttp.send(`question_id=${questionId}&selected_answer=${selectedAnswer}`);
}


    document.getElementById('answer-form').addEventListener('submit', handleSubmit);

    </script>

    <div class="choice-container">
        {% for choice in question.choices|slice:":2" %}
        <div class="choice-item">
            <button type="button" class="choice-btn" onclick="handleChoiceClick(this)">{{ choice }}</button>
        </div>
        {% endfor %}
        {% for choice in question.choices|slice:"2:" %}
        <div class="choice-item">
            <button type="button" class="choice-btn" onclick="handleChoiceClick(this)">{{ choice }}</button>
        </div>
        {% endfor %}
    </div>


    <!-- <div class="alert-error"> -->
        <div id="result-container">
            <div id="result-message"></div>
            <div id="action-buttons">
                <button type="submit" id="submit-btn" disabled>Submit Answer</button>
                <button id="next-btn" onclick="handleNextClick()" disabled>Next</button>
            </div>
            
        </div>
        
    <!-- </div> -->
    

    
    
  </form>
  

    <script>
        function handleNextClick() {
            window.location.href = "{% url 'test' %}";
        }
    </script>

</div>

    
{% endblock %}